version: "3.8"

services:
  blogi-back:
    image: blogilista-backend-dev
    volumes:
      - ./blogilista:/usr/src/app
      - /usr/src/app/node_modules/
    environment:
      - NODE_ENV=development
    ports:
      - 3001:3000
