version: "3.8"

services:
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy

  blogi-back:
    image: blogilista-backend-prod
    build:
      context: ./blogilista
      dockerfile: ./blogilista/Dockerfile
    volumes:
      - ./blogilista:/usr/src/app
      - /usr/src/app/node_modules/
    environment:
      - NODE_ENV=production
    ports:
      - 3001:3001

  blogi-front:
    image: blogilista-frontend-prod
    build:
      context: ./blogilista-front
      dockerfile: ./blogilista-front/Dockerfile
    volumes:
      - ./blogilista-front:/usr/src/app
    ports:
      - 3000:80
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3001
      - CHOKIDAR_USEPOLLING=true
